### ISSUE TITLE
Make `+` implicitly convert int to str when adding to str.

### ISSUE THREAD

**Issue by Lyxal** [GingerIndustries/Etch#6]
This would be really cool and most languages don't do it and that's really sad so make etch do it because that'd be great and everyone would be happy. Just the concatenation, not the actual addition like JS does don't do what JS does that'd be a horrible idea just make it concatenation as if you were writing `string + str(number)` thank you have a good day.

**Comment by GingerIndustries** [comment]
I can do that I guess

**Comment by GingerIndustries** [comment]
This will be added in #9.
